{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.threejsnative",
    "module": "tjn-engine",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tjn-engine-1.0.0.aar",
          "url": "tjn-engine-1.0.0.aar",
          "size": 1597871,
          "sha512": "ca31eebbabb0af0edf69459064ed6c78fc54ab079edae5435fad79879a475def94b01c9c75a6e3517970c0906ee3f4304916065b46fe03c17918e13b91fe275b",
          "sha256": "0f76b3154ba50ac9d3f94e4ad3463f3468a18ab5355932188fdecf776bb83a5d",
          "sha1": "7d669ad5853bcabcadfdf3d730d786e4e14afab0",
          "md5": "5198f25f3e77365eafccfa699e67ca5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tjn-engine-1.0.0.aar",
          "url": "tjn-engine-1.0.0.aar",
          "size": 1597871,
          "sha512": "ca31eebbabb0af0edf69459064ed6c78fc54ab079edae5435fad79879a475def94b01c9c75a6e3517970c0906ee3f4304916065b46fe03c17918e13b91fe275b",
          "sha256": "0f76b3154ba50ac9d3f94e4ad3463f3468a18ab5355932188fdecf776bb83a5d",
          "sha1": "7d669ad5853bcabcadfdf3d730d786e4e14afab0",
          "md5": "5198f25f3e77365eafccfa699e67ca5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tjn-engine-1.0.0-sources.jar",
          "url": "tjn-engine-1.0.0-sources.jar",
          "size": 11317,
          "sha512": "66be51ed49faa8161b8b309e928c0c8d09e684e68deeb891c87c56e27ba850137a5716f039b481a20370db3c2d75faa791b5ed3e79a147a7ff27d521ceae61ff",
          "sha256": "25574670660c999f3f8c1063a883382dec977aa3a51af594adb898040b134ad0",
          "sha1": "0f3a67e91cb5a993efde2cdd6a00166b1eb458eb",
          "md5": "cfe34b68dd88a8bf7b84ff65dadf50f4"
        }
      ]
    }
  ]
}
