{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.threejsnative",
    "module": "tjn-engine",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tjn-engine-1.0.1.aar",
          "url": "tjn-engine-1.0.1.aar",
          "size": 1597825,
          "sha512": "4f4427bc94a10100537a193d82792ab7cf7b235c6f4c6bb8272d9c3f2b79bcbe47fa6efff21f7b3c11084deec6eaf49c58fc82e22636c8cb9699f272806e9229",
          "sha256": "b0acac1ba10cd9bacb53bed5ae321fa5ae1e47bb3c01a858801142fe45dca3b4",
          "sha1": "6469f8c8cf47466ea9c412ac5dc16eb36ff13001",
          "md5": "076bad57592287042499d0ea241da84e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tjn-engine-1.0.1.aar",
          "url": "tjn-engine-1.0.1.aar",
          "size": 1597825,
          "sha512": "4f4427bc94a10100537a193d82792ab7cf7b235c6f4c6bb8272d9c3f2b79bcbe47fa6efff21f7b3c11084deec6eaf49c58fc82e22636c8cb9699f272806e9229",
          "sha256": "b0acac1ba10cd9bacb53bed5ae321fa5ae1e47bb3c01a858801142fe45dca3b4",
          "sha1": "6469f8c8cf47466ea9c412ac5dc16eb36ff13001",
          "md5": "076bad57592287042499d0ea241da84e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tjn-engine-1.0.1-sources.jar",
          "url": "tjn-engine-1.0.1-sources.jar",
          "size": 11317,
          "sha512": "66be51ed49faa8161b8b309e928c0c8d09e684e68deeb891c87c56e27ba850137a5716f039b481a20370db3c2d75faa791b5ed3e79a147a7ff27d521ceae61ff",
          "sha256": "25574670660c999f3f8c1063a883382dec977aa3a51af594adb898040b134ad0",
          "sha1": "0f3a67e91cb5a993efde2cdd6a00166b1eb458eb",
          "md5": "cfe34b68dd88a8bf7b84ff65dadf50f4"
        }
      ]
    }
  ]
}
